=== SturgisRaphael/TPXML/TP3/Enseignement.dtd
<?xml version="1.0" encoding="utf8" ?>

<!ELEMENT Master    (UE+, Intervenants)>
<!ELEMENT UE		(nom, nbCredits, resume, plan, lieuEns, ref-Intervenant+)>

<!ATTLIST UE	id	ID	#REQUIRED>

<!ELEMENT Intervenants	(Intervenant*)>
<!ELEMENT Intervenant	(nom, adrElect,adrSiteWeb)>

<!ATTLIST Intervenant	id	ID	#REQUIRED>

<!ELEMENT nom			(#PCDATA)>
<!ELEMENT nbCredits		(#PCDATA)>
<!ELEMENT resume		(#PCDATA)>
<!ELEMENT plan			(#PCDATA)>
<!ELEMENT adrElect		(#PCDATA)>
<!ELEMENT adrSiteWeb	(#PCDATA)>

<!ELEMENT lieuEns		(Luminy|StCharles)>

<!ELEMENT Luminy		EMPTY>
<!ELEMENT StCharles		EMPTY>

<!ELEMENT ref-Intervenant	EMPTY>
<!ATTLIST ref-Intervenant	ref	IDREF	#REQUIRED>

<!ELEMENT Parcours 		(Responsables, nom, resume, Debouches, Semestre*)>

<!ELEMENT Responsables	(ref-Intervenant+)>

<!ELEMENT Debouches		(Debouche*)>

<!ELEMENT Debouche		(#PCDATA)>

=== SturgisRaphael/TPXML/TP3/Enseignement.xml
<?xml version="1.0" encoding="utf8" ?>
<!DOCTYPE Cursus SYSTEM "Enseignement.dtd">


<Master>
  <UE id="abcd1">
    <nom> XML </nom>
  	<nbCredits> 30 </nbCredits>
  	<resume> BLBLBLBLLBLBLBBL </resume>
  	<plan> B </plan>
  	<lieuEns><Luminy/></lieuEns>
  	<ref-Intervenant ref="Wissam"/>
  </UE>
  <UE id="azertyuiop">
	<nom></nom>
	<nbCredits></nbCredits>
	<resume></resume>
	<plan></plan>
	<lieuEns>
		<StCharles/>
	</lieuEns>
  	<ref-Intervenant ref="Wissam"/>
  </UE>
	<Intervenants>
		<Intervenant id="Wissam">
			<nom></nom>
			<adrElect></adrElect>
			<adrSiteWeb></adrSiteWeb>
		</Intervenant>
	</Intervenants>
</Master>
